### ISSUE TITLE
panic on TypeNameMismatch

### ISSUE THREAD

**Issue by taikulawo** [Lucretiel/kaydle#14]
I'm trying parse follow txt, but get
```
called `Result::unwrap()` on an `Err` value: TypeNameMismatch { node_name: "server_name", type_name: "ServerBlock" }
```

reproduce text
```
worker_processes  1
events {
    worker_connections  1024
}


http {
    include       "mime.types"
    server {
        server_name  "localhost"
        location "/" {
            root   "html"
            index  "index.html" "index.htm"
        }
        location "/" {
            root   "html"
            index  "index.html" "index.htm"
        }
        
    }
    server {
        server_name  "localhost"
        location "/" {
            root   "html"
            index  "index.html" "index.htm"
        }
        location "/" {
            root   "html"
            index  "index.html" "index.htm"
        }
        
    }

}
```

**Comment by taikulawo** [comment]
here are repo https://github.com/taikulawo/languages/blob/master/rust/src/bin/kdl.rs

**Comment by Lucretiel** [comment]
I'm not sure if there's yet a good way in kaydle to handle lists of sibling nodes like this— each set of children is modeled either as a uniformly typed list of nodes, or as a record containing node names. Figuring out how to model something resembling `include: String, server: Vec<Server>` is on my long term roadmap (though I suspect it may not be possible to make this compatible with the serde model).

**Comment by taikulawo** [comment]
Ok, I got it. I use kdl-rs to do it manually. thank you :)
